services:
  # --- ZOOKEEPER (Zarządca Kafki) ---
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    restart: on-failure

  # --- KAFKA (Centralna Szyna Danych) ---
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      # TUTAJ WPISUJESZ SWOJE IP TYLKO DLA ZEWNĘTRZNYCH URZĄDZEŃ
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://10.10.133.187:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  # --- BAZA DANYCH (TimescaleDB) ---
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin          # <-- DODAJ TO
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=agv_db
    volumes:                                      # <-- DODANE: Pamięć bazy danych
      - postgres_data:/var/lib/postgresql/data

  # --- WIZUALIZACJA ANALITYCZNA (Grafana) ---
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - timescaledb
    volumes:                                      # <-- DODANE: Pamięć dashboardów
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer

  # --- MODUŁ A (Emulator AGV) ---
  edge-emulator:
    build: ./edge-emulator
    depends_on:
      - kafka
    environment:
      - KAFKA_SERVER=kafka:9092
    restart: on-failure

  data-consumer:
    build: ./edge-emulator
    command: ["python", "-u", "consumer.py"] 
    depends_on:
      - kafka
      - timescaledb
    environment:
      - PYTHONUNBUFFERED=1
    restart: on-failure

  edge-processor:
    build: ./edge-emulator
    command: ["python", "-u", "edge_processor.py"] 
    depends_on:
      - kafka
    environment:
      - PYTHONUNBUFFERED=1
    restart: on-failure

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - timescaledb
    restart: on-failure

  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    volumes:                  
      - ./frontend:/app
    depends_on:
      - kafka
    restart: on-failure
  # --- MODUŁ B: ANALITYKA BIG DATA (Apache Spark) ---
  spark-analytics:
    build: ./spark-analytics
    depends_on:
      - kafka 
    ports:                  # <--- DODAJ TO
      - "4040:4040"         # <--- DODAJ TO
    environment:                 # <-- DODAJ TO
      - PYTHONUNBUFFERED=1
    volumes:                      # <-- DODAJ TO
      - ./spark-analytics:/app
    restart: on-failure
    

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=AGV_Cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka
    restart: on-failure

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - timescaledb
    restart: on-failure
# <-- DODANE NA SAMYM DOLE: Deklaracja sejfów na dysku
volumes:
  postgres_data:
  grafana_data: